version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=testdb
      - DB_USER=root
      - DB_PASSWORD=secret
      - ALLOWED_DOMAIN=example.com
      - TZ='Europe/Moscow'
      - PHP_IDE_CONFIG=serverName=Docker
    extra_hosts:
      - host.docker.internal:host-gateway

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
